import type { Budget, DietConstraint, Fulfilment, Mood } from '../../domain'

// Every user-facing string (m1-spec §2.1). UK English, sentence case, plain.
// The product name is a neutral placeholder in ONE place and is not part of the design system.

export const PRODUCT_NAME = 'Crave'

export const copy = {
  welcome: {
    issue: 'Issue no. 01',
    strap: 'For the undecided',
    title: 'Hungry? Can’t decide?',
    body: 'Swipe a few dishes. We’ll work out the one you want.',
    // Matches the engine's baseline: a median of 9 swipes to a decision (docs/m0-report.md).
    swipes: { about: 'About', count: '10', unit: 'swipes' },
    primary: 'Just me',
    withFriends: 'With friends',
    soon: 'Soon',
    withFriendsLabel: 'With friends, coming soon',
    secondary: 'Back issues',
    loading: 'Getting the menu ready…',
    loadError: "We couldn't load the dishes. Please refresh the page.",
  },
  craving: {
    contents: 'Contents',
    title: 'What’s the craving?',
    body: 'Pick up to two. It only counts for tonight.',
    tonight: 'Tonight',
    filters: 'Filters',
    somethingNew: 'Something new',
    noIdea: 'I have no idea',
    primary: 'Start swiping',
    back: 'Back',
    diet: 'Diet',
    budget: 'Budget',
    eating: 'Eating',
    tooTight: (n: number) =>
      `Only ${n} ${n === 1 ? 'dish fits' : 'dishes fit'} these settings, so there's less to choose from. You can still carry on.`,
    none: 'No dishes match these settings. Try a wider budget or a different eating option.',
    raiseBudget: (label: string, n: number) => `Raise budget: ${label} (${n} ${n === 1 ? 'dish' : 'dishes'})`,
  },
  moods: {
    spicy: 'Spicy',
    comforting: 'Comforting',
    carby: 'Carby',
    fresh: 'Fresh',
    indulgent: 'Indulgent',
    warm_soupy: 'Warm & soupy',
    sweet: 'Sweet',
  } satisfies Record<Mood, string>,
  diet: {
    none: 'None',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    pescatarian: 'Pescatarian',
    no_pork: 'No pork',
    gluten_free: 'Gluten-free',
  } satisfies Record<DietConstraint | 'none', string>,
  budget: { any: 'Any', low: 'Up to £10', mid: 'Up to £16', high: 'Up to £25' } satisfies Record<Budget, string>,
  fulfilment: { either: 'Either', delivery: 'Delivery', go_out: 'Going out' } satisfies Record<Fulfilment, string>,
  sheets: {
    dietTitle: 'Diet',
    dietBody:
      'We only show dishes that fit. Allergens are shown only when a venue lists them; always check with the venue.',
    budgetTitle: 'Budget',
    budgetBody: 'We only show dishes priced at or under your limit.',
    eatingTitle: 'Eating',
    done: 'Done',
    close: 'Close',
  },
  deck: {
    undo: 'Undo',
    close: 'Close',
    decide: 'Decide for me',
    card: (n: number) => `Card ${n}`,
    progress: { more: 'a few more', nearly: 'nearly there' },
    nope: 'Nope',
    yes: 'Yes',
    theOne: "That's the one",
    cardHint: 'Arrow right for yes, arrow left for nope, Enter for that’s the one.',
    heading: (name: string, n: number) => `${name}, card ${n}`,
    announce: (n: number, label: string, progress: string) =>
      `Card ${n}. ${label} ${progress[0]!.toUpperCase()}${progress.slice(1)}.`,
    spice: (n: number, word: string) => `Spice ${n} of 4, ${word.toLowerCase()}`,
    allergens: 'Listed allergens',
    inside: 'Inside',
  },
  match: {
    title: 'Match found',
    kicker: 'Tonight’s cover',
    at: (venue: string, price: string, distance: string) => `at ${venue} · ${price} · ${distance}`,
    why: 'Why this one',
    orTry: 'Or try',
    ourMatch: 'Our match',
    alsoAt: 'Also at',
    order: 'Order',
    directions: 'Get directions',
    save: 'Save',
    saved: 'Saved',
    somethingElse: 'Show me something else',
    startAgain: 'Start again',
    pickTitle: 'Pick one of these',
    pickBody: 'None of our picks landed, so here are the closest five.',
    // Runner-up inspection (approved copy: "Alternative")
    altLabel: 'Alternative',
    altWhy: 'Why it could suit you',
    altChoose: 'Choose this instead',
    altReturn: 'Return to our match',
    // Pick-list sessions only (none of our picks landed, so there is no "our match" to return to).
    pickListReturn: 'Back to the list',
    pickListTop: 'Top of the list',
  },
  error: {
    title: 'Something went wrong',
    body: 'Sorry, that screen didn’t load. Starting again usually fixes it.',
    restart: 'Start again',
  },
  imagery: {
    illustrative: 'Illustrative image',
    illustrativePlural: 'Illustrative images',
  },
  handoff: {
    orderTitle: (venue: string) => `Order from ${venue}`,
    orderBody: 'Choose a delivery app.',
    directionsTitle: (venue: string) => `Directions to ${venue}`,
    openMaps: 'Open in Maps',
    prototype: 'Prototype: this isn’t connected yet. In the real app it would open the app you choose.',
    mapsPrototype: 'Prototype: this isn’t connected yet. In the real app it would open your maps app.',
    opened: (platform: string, venue: string) => `In the real app, this would open ${platform} at ${venue}.`,
    mapsOpened: 'In the real app, this would open your maps app with walking directions.',
  },
  saved: {
    kicker: 'Saved',
    title: 'Back issues',
    body: 'The dishes you kept.',
    issue: (n: number, date: string) => `No. ${String(n).padStart(2, '0')} · ${date}`,
    empty: 'No back issues yet. Save tonight’s cover and it will appear here.',
    emptyAction: 'Find tonight’s dish',
    remove: 'Remove',
    back: 'Back',
    savedOn: (date: string) => `Saved ${date}`,
    missing: 'That saved dish is no longer here.',
  },
  empty: {
    noCards: "We've run out of dishes to show you. Here's our best guess.",
  },
} as const
